# Generated by Django 5.2.9 on 2025-12-08 15:00

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_documentembedding_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentembedding',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=768),
        ),
    ]
